@echo off
echo Starting MDLAB Direct Backend for Network Access...
echo.
echo Stopping MongoDB service...
net stop MongoDB
echo.
echo Starting MongoDB with network binding...
start "" "C:\Program Files\MongoDB\Server\8.0\bin\mongod.exe" --bind_ip 0.0.0.0 --port 27017 --dbpath "C:\Program Files\MongoDB\Server\8.0\data"
echo.
echo Waiting for MongoDB to start...
timeout /t 5
echo.
echo Starting backend server...
node server.js